### ISSUE TITLE
Feedback handleidingen kubussen

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/JiveDocumentation#10]
@joostschouppe 
<p>Ik vond de handleiding heel nuttig, ze heeft me goed geholpen om de kubussen in PinC te krijgen. Nog enkele puntjes van feedback:<p>
<ul>
<li>Er staat in de basishandleiding niet uitgelegd hoe nieuwe dimensies/dimensieniveaus aan te maken wanneer ze nog niet bestaan in PinC. Een printscreen hiervan zou ook nuttig zijn denk ik.</li>
<li>Volgende puntje in de handleiding was verwarrend, vond ik: 'Voor dimensies die al in andere kubussen zitten (zie stap 1): de kolomtitel=de dimensiecode en de categorieën=itemcodes' =>moet dat niet de dimensie<i>niveau</i>code zijn?</li>
<li>Vicky had me eerst al even via teams (scherm delen) getoond hoe het werkt, en dat hielp ook wel, omdat ik het al eens had gezien. In de handleiding zitten al enkele printscreens wat nuttig is, maar een filmpje van heel het proces met screen recorder erbij zou evt. ook wel handig zijn (hoewel dat misschien ook wel een beetje ‘overkill’ is, ik veronderstel niet dat er zo vaak nieuwe mensen starten, maar ik geef het maar mee)</li>
<li>Ik zou de drie handleidingen integreren in één. Of, als je toch het onderscheid tussen de drie wil houden, één ‘geïntegreerde’ handleiding als extra toevoegen. De uitleg over onderwerp maken obv kubus heb ik immers aan Vicky gevraagd, omdat ik dat in de basishandleiding niet terugvond. Op het startscherm rond kubussen staat het wel vrij duidelijk weergegeven als  ‘Kubussen als bron voor onderwerpen.md’ dus ten dele ligt dat ook wel aan mij, ik had niet goed gekeken. Maar ’t zou handiger zijn als dat geïntegreerd in 1 handleiding zat zodat je dat ook snel met zoekfunctie kan terugvinden.</li>
<li>De SPSS syntax vond ik persoonlijk minder nuttig. Verschillende collega’s werken in SAS, zelf heb ik m’n scriptje in R gemaakt, ik heb vernomen dat Chris van Oost-Vlaanderen met Python aan het experimenteren is… op zich kan die wel blijven staan, maar ik zou de uitleg erbij eventueel opentrekken naar het advies dat werken met een script het gemakkelijkste is voor updates in de toekomst. Ik zou daarnaast ook enkele meer algemene aandachtspunten ivm de opmaak van de bestanden meegeven, nl. dat je op het laagste beschikbare geoniveau moet inladen, opletten met fusiegemeentes, etc. (hoewel dat mss al ergens in een meer algemene handleiding staat opgenomen?)</li>
<li>Vicky had voor mij een sjabloon gemaakt om mijn kubusbestand in aan te maken. Op zich staat er ook wel een print screen dat je kan gebruiken om zelf de structuur aan te maken. Maar ik zou het toch nuttig vinden als zo’n sjabloon als .xlsx mee kan worden gedownload bij de handleiding. In een tweede tabblad had ze bijvoorbeeld ook de dimensieniveaus al wat inzichtelijker gemaakt, ik vond dat wel nuttig. Ik geef het hier ook mee als voorbeeld.</li>
</ul>
https://github.com/provinciesincijfers/JiveDocumentation/files/5944706/sjabloon.kubus2371.2.xlsx

**Comment by joostschouppe** [comment]
Nog aan te vullen: gebruik van niet-aggregeerbare dimensies. Bij diemnsion level "aggregate type" = "no aggregation". Voorbeeld:

Nu wordt als je de kubus opvraagt dus niet meer standaard iets fouts getoond, maar krijg je in de plek een kruising van alles met alles (ook niet echt handig, maar beter dan fout).

In de bediening moet je dan steeds minstens één dimensie-item overhouden om een presentatie te kunnen maken. Zie 
https://provincies.incijfers.be/admin/jive?var=kubus2603_overnachtingen
