### ISSUE TITLE
Code rapport kubussen 

### ISSUE THREAD

**Issue by anneliesvs** [provinciesincijfers/JiveDocumentation#7]
Kan je de code van dit rapport op de github zetten? (https://provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_top10 )

**Comment by StephaniePeeters** [comment]
Je moet deze regel toevoegen in je class bij de CSS (achter het oogje).

<ShowFirstN>10</ShowFirstN>

**Comment by joostschouppe** [comment]
Toegevoegd: https://github.com/provinciesincijfers/JiveDocumentation/blob/master/rapporten/voorbeelden-pinc/sjabloon_top10.sw5r
