### ISSUE TITLE
omzetting webpagina Arvastat naar rapport

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/JiveDocumentation#9]
@joostschouppe 

Zijn er instructies over hoe je een webpagina omzet naar een rapport ==> Zie rapport Arvastat – Antwerpen    [https://stadincijfers.antwerpen.be/databank/Jive/Report?id=arvastat_werkloosheid

Alvast bedankt.

**Comment by joostschouppe** [comment]
In bijlage de code voor deze oefening:
[Report_637202891958075557.zip](https://github.com/provinciesincijfers/JiveDocumentation/files/4358282/Report_637202891958075557.zip)

Voor "een webpagina": bij Arvastat kan dit, omdat hun pagina aangestuurd wordt op basis van een niscode, en we die handmatig of automatisch kunnen invullen binnen Swing. En Aravastat biedt een "uitgeklede" versie van hun site aan, waardoor je het er goed kunt doen uitzien. Bij andere sites kan dat allemaal anders liggen, en dus moeilijker zijn.
